heat_template_version: 2013-05-23

description: |
  A heat template to deploy a PHP application under Apache

parameters:

  server_hostname:
    description: Server Name
    type: string
    default: php

  image:
    description: Server Image
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)

  flavor:
    description: Rackspace Cloud Server flavor
    type: string
    default: 4 GB Performance

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string
    default: php-app

  revision:
    description: Git Branch/Ref
    type: string
    default: HEAD

  packages:
    description: PHP Packages
    type: string
    default: ''

  repo:
    description: Git Repo URL
    type: string
    default: ''

  url:
    description: URL for site
    type: string
    default: 'http://example.com'

  deploy_key:
    description: Git deploy key for private repositories.
    type: string
    default: ''

  destination:
    description: Deploy Directory
    default: /var/www/vhosts/application
    type: string

  public:
    description: The public facing directory of your application relative to the destination.
    type: string
    default: /

  sslcert:
    description: SSL Certificate
    type: string
    default: false

  sslkey:
    description: SSL Key
    type: string
    default: false

  sslcacert:
    description: SSL CA Certificate
    type: string
    default: false

  varnish:
    description: Install Varnish
    type: string
    default: false

  ssh_private_key:
    description: Private key so OS::Heat::Chef can access the server
    type: string

  http_port:
    description: HTTP Port
    type: string
    default: 80

  https_port:
      description: HTTPS Port
      type: string
      default: 443

  memcached_size:
    description: Memcached memory size limit
    type: number
    default: 128

  ssh_keypair_name:
    description: keypair name
    type: string

resources:

  php_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }

  bootstrap_server:
    type: "OS::Heat::ChefSolo"
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [php_server, accessIPv4] }
      Berksfile: |
        site :opscode

        cookbook 'apt'
        cookbook 'build-essential'
      node:
        run_list: ["recipe[apt]",
                   "recipe[build-essential]"]

  php_setup:
    type: "OS::Heat::ChefSolo"
    DependsOn: bootstrap_server
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [php_server, accessIPv4] }
      Berksfile: |
        site :opscode

        cookbook 'build-essential'
        cookbook 'apt'
        cookbook 'chef-client'
        cookbook 'apache2'
        cookbook 'mysql'
        cookbook 'application',
          :git => 'https://github.com/opscode-cookbooks/application.git'
        cookbook 'application_php',
          :git => 'https://github.com/opscode-cookbooks/application_php.git'
        cookbook 'php'
        cookbook 'firewall',
          :git => 'https://github.com/opscode-cookbooks/firewall.git',
          :ref => 'c9473bcb3d666dc053979852042cef75236978fe'
        cookbook 'php_app',
          :git => 'https://github.com/JasonBoyles/php_app.git'
        cookbook 'memcached'
        cookbook 'ssh_known_hosts'
        cookbook 'varnish'
        cookbook 'php-ioncube',
          :git => 'https://github.com/werdan/php-ioncube.git',
          :ref => 'b663cb2a5fdcdc38564195603dc4c082517dc155'
        cookbook 'rax_php_app',
          :git => 'https://github.com/JasonBoyles/rax_php_app.git'

      node:
        php_app:
          destination: { get_param: destination }
          deploy_key: { get_param: deploy_key }
          http_port: { get_param: http_port }
          https_port: { get_param: https_port }
          packages: { get_param: packages }
          public: { get_param: public }
          repo: { get_param: repo }
          rev: { get_param: revision }
          sslcert: { get_param: sslcert }
          sslkey: { get_param: sslkey }
          sslcacert: { get_param: sslcacert }
          url: { get_param: url }
          varnish: { get_param: varnish }
        varnish:
            backend_host: 127.0.0.1
        run_list: ["recipe[memcached]",
                   "recipe[rax_php_app]",
                   "recipe[php-ioncube]"]
